apiVersion: v1
kind: Pod
metadata:
  name : ${PROJECT_NAME}
spec:
  containers:
  - name: ${PROJECT_NAME}
    image: ${REPOSITORY}
    args: ["yarn", "run", "serve"]
    ports:
    - containerPort: 80
    volumeMounts:
      - mountPath: /keys
        name: key-cvfactory
  volumes:
    - name: key-cvfactory
      secret:
        secretName: key-cvfactory
