apiVersion: apps/v1
kind: Deployment
metadata:
  name : ${PROJECT_NAME}
spec:
  selector:
    matchLabels:
      app: ${PROJECT_NAME}-app
  replicas: 1
  template:
    metadata:
      labels:
        app: ${PROJECT_NAME}-app
    spec:
      containers:
        - name: ${PROJECT_NAME}-app
          image: ${REPOSITORY}
          args: ["yarn", "run", "serve"]
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /keys
              name: key-${PROJECT_NAME}
      volumes:
        - name: key-${PROJECT_NAME}
          secret:
            secretName: key-${PROJECT_NAME}
